package:
  name: gumath
  version: 0.2.0dev3

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY', 'NA') }}_{{ environ.get('GIT_BUILD_STR', 'NA') }}

test:
  files:
    - test
  commands:
    - python test/test_gumath.py
  requires:
    - libndtypes ==0.2.0dev3
    - libxnd ==0.2.0dev3
    - libgumath ==0.2.0dev3
    - ndtypes ==0.2.0dev3
    - xnd ==0.2.0dev3
    - nomkl # [not win]
    - numpy
    - numba
    - python ==3.7

requirements:
  build:
    - libndtypes ==0.2.0dev3
    - libxnd ==0.2.0dev3
    - libgumath ==0.2.0dev3
    - ndtypes ==0.2.0dev3
    - xnd ==0.2.0dev3
    - python ==3.7
  run:
    - libndtypes ==0.2.0dev3
    - libxnd ==0.2.0dev3
    - libgumath ==0.2.0dev3
    - ndtypes ==0.2.0dev3
    - xnd ==0.2.0dev3
    - python ==3.7

about:
  home: https://github.com/plures/
  license: BSD 3-clause

source:
  git_url: ../../
